server {
        listen               80;
        server_name          shared.<cedar.CEDAR_HOST>;
        return               301 https://shared.<cedar.CEDAR_HOST>$request_uri;
}

server {
        listen               443 ssl;
        server_name          shared.<cedar.CEDAR_HOST>;

        include              cedar/inc/ssl-common.conf;

        ssl_certificate     /usr/local/etc/certificates/certs/shared.<cedar.CEDAR_HOST>/shared.<cedar.CEDAR_HOST>.crt;
        ssl_certificate_key /usr/local/etc/certificates/certs/shared.<cedar.CEDAR_HOST>/shared.<cedar.CEDAR_HOST>.key;

        add_header           'Access-Control-Allow-Origin' '*';
        add_header           'Access-Control-Allow-Methods' 'GET';

        location / {
                alias        /usr/local/etc/shared-data/;
        }

        error_log            /etc/nginx/log/nginx-frontend-shared/nginx-error.log warn;
        access_log           /etc/nginx/log/nginx-frontend-shared/nginx-access.log combined if=$loggable;
}
