upstream cedar-frontend-workspace {
        server <cedar.CEDAR_FRONTEND_WORKSPACE_HOST>:4201;
}

server {
        listen               80;
        server_name          workspace.<cedar.CEDAR_HOST>;
        return               301 https://workspace.<cedar.CEDAR_HOST>$request_uri;
}

server {
        listen               443 ssl;
        server_name          workspace.<cedar.CEDAR_HOST>;

        include              cedar/inc/ssl-common.conf;

        ssl_certificate     /usr/local/etc/certificates/certs/workspace.<cedar.CEDAR_HOST>/workspace.<cedar.CEDAR_HOST>.crt;
        ssl_certificate_key /usr/local/etc/certificates/certs/workspace.<cedar.CEDAR_HOST>/workspace.<cedar.CEDAR_HOST>.key;

        location / {
                proxy_pass   http://cedar-frontend-workspace;
        }

        error_log            /etc/nginx/log/nginx-frontend-workspace/nginx-error.log warn;
        access_log           /etc/nginx/log/nginx-frontend-workspace/nginx-access.log combined if=$loggable;
}
